### PR TITLE
Improved (annoying) messages

### PR DESCRIPTION
**Pull request by Defeater**
Just improve and remove some annoying messages.

### CODE REVIEW

**Comment by necropotame** [comment]
* Infect a humain is more difficult than kill an infected. This is why infect a human increase the score by 2 while kill an infected increase the score by 1. 
* I add a chat message about infection since it is very important to know who become infected. But I agree that the same information is available in the top right corner of the screen. I will think about remove it or not.
* For the rest, I will merge your version when I have time.

**Comment by Defeater** [comment]
- For a zombie, its normal to infect a human. And for a human, its normal to kill a zombie. If the one thing is more difficult than the other, then the game is not balanced. 
Perhaps there should be a bonus for killing the last standing human, or the human with the best score.
- Why is this important? If you play in a team, you see the other player. If you want to play in a team, you have the socreboard. 16 players = 16 annoying messages.
- Okay ;)

**Comment by necropotame** [comment]
* Normal doesn't mean easy or difficult. Since zombies can have infinite number of life while humans are liimited by definition to one, it's logical that humans kill more zombies that zombies infected humans. In fact human can easly kill more than 30 zombies in one round. Zombies can only infect 16 humans. That's why the score is different.
* Is the team is separated in two groups, like in inf_skull ? We will see :-)

**Comment by Defeater** [comment]
- Okay, now I understand what you mean. Whats with a bonus for the last surviving human?
- Maybe. I think we should made these messages configurable via a variable (on or off).

**Pull request merged**
