### PR TITLE
Finished translating Italian language

### PR DESCRIPTION
**Pull request by rotolonico**
All the it.txt file is now fully translated!

-Ñı©Ø

### CODE REVIEW

**Comment by rotolonico** [comment]
Ty 😀

Your teeworlds nickname is necropotame?

2016-10-01 19:48 GMT+02:00 necropotame <notifications@github.com>:

**Comment by necropotame** [comment]
Yes, it's necropotame. And to be sure, I'm always connected to my InfClass account, so I've a @ ;)

**Comment by rotolonico** [comment]
When will the server be updated with the new translated changes? Also I
just tried the italian translated version and some other translations were
a bit messed up... maybe I'll check them later and fix them...

Instead of: The match has finished in (time) in italian the translation is:
The meet has finished in (time) so, maybe I should fix that when upload
these new changes!

2016-10-01 20:59 GMT+02:00 necropotame <notifications@github.com>:

**Comment by SantX27** [comment]
It was my fault, I'm not good making translations

**Comment by necropotame** [comment]
You can both complete the translation on https://www.transifex.com/teeuniverses/infclass

This is our new portal to works on translations.

**Comment by rotolonico** [comment]
Alright dude, that website is amazing! I translated all the Italian
language!

2016-11-04 12:28 GMT+01:00 necropotame <notifications@github.com>:

**Comment by rotolonico** [comment]
BOOM! Everything translated! Also I really love the new hero class!

2016-11-04 21:33 GMT+01:00 Domenico Rotolo <rotolonico@gmail.com>:

**Comment by rotolonico** [comment]
Hi, I'm translating infclass back again... I need some help with this part:

and besides, death bereaves him of his nourishment.

I don't know if I understood it too well but I think it means that when he
is out of food he starves to death... tell me if I'm right

2016-11-04 21:36 GMT+01:00 Domenico Rotolo <rotolonico@gmail.com>:

**Comment by Henningstone** [comment]
This sentence makes no sense, see for example [this dictionary](http://www.thefreedictionary.com/bereave).

At best it could mean that if you are dead, you won't be able to eat anymore (like as if that would be the thing you'd miss most lol)

**Comment by necropotame** [comment]
Henningstone, according to your link, it means that "nourishment" is valuable for the ghoul and that it is taken by death. Which corresponds to what happens in the game. This sentence should be replace by something like "and besides, he lost some of his nourishment when he dies".
(btw, Socialdarwinist made this sentences)

**Comment by Socialdarwinist** [comment]
Much meaning has been conveyed in two well-picked words. If you want to imagine the functioning of the ghoul in a technical manner, you might be inclined to hear something like that “his charge leaks” or similar mechanistic contrivances; but we want the players to immerse into the game in a way they do not get suggested that it be merely a computer program. Therefore, the ghoul rationale has been enclosed with a twang of canty wildness. It is just aporetic that the text hitting the nail on the head in relation to the purpose of chirking the consuetudinary English speaker makes pudders when presented for the distinctly intricate purpose of translation.

**Comment by Henningstone** [comment]
Socialdarwinist, I know that you like obfuscating what you want to express (your last comment contains at least 5 words that can not even be found in a multilingual dictionary), but still I hold for sentences that can at least be understood by normal people, you know... this is not 1850

**Pull request merged**
