### PR TITLE
added 2 files to ignore list

### PR DESCRIPTION
**Pull request by duralakun**
Another huge update

### CODE REVIEW

**Comment by necropotame** [comment]
Those files are related to your personal workspace, and are not generated by InfClass, no?

**Comment by duralakun** [comment]
yes they are not generated, but i keep them right next to the other files, so i thought it would be usefull to add them to the ignore list. You disagree?

**Comment by necropotame** [comment]
If everyone add it's own file, it will be a mess. You can add those files in your global gitignore. Create a file $HOME/.config/git/ignore, and add them inside :)

**Comment by Socialdarwinist** [comment]
For those Unix-like system users who come hither coincidentally I write this, because it is regularly not exposed orderly on the web: Git, to ignore files, uses [patterns](https://git-scm.com/docs/gitignore) in

1. a .gitignore in a repository, that is by its nature the only ignore file regularly shared with the public.
2. a repository-wide (“local”) file .git/ignore/exclude in each repository laid down by git. The used path for a repository-wide private ignore file could be changed in the .git/config of the repository, but there is no reason to do this.
3. a per-user (“global”) file determined by the [.gitconfig variable core.excludesFile](https://git-scm.com/docs/git-config#git-config-coreexcludesFile) of the user specified in ~/.gitconfig, put down as
 ```
[core]

    excludesfile = "the path to the ignore file desired"
```
and to be created in the desired path or, with the default value of the variable, at /.config/git/ignore.

4. a system-wide file (that might be arguable inside of organizations that have multiple programmers working on one system) determined by the like variable specified in /etc/gitconfig put down in the like manner, where the system-wide gitconfig as well as the ignore file has to be created.

**Pull request closed without merging**
