### PR TITLE
Give full armor to zombies when they are the only zombie in the game.

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by Socialdarwinist** [comment]
```
[17-05-26 22:49:08][chat]: pinkieval: I sent a patch to give full armor to zombies when they are alone
[17-05-26 22:49:19][chat]: pinkieval: waiting for Socialdarwinist to merge it ^^
[17-05-26 22:49:27][chat]: Socialdarwinist: pinkieval: Hm, what about it being rather random?
[17-05-26 22:49:36][chat]: pinkieval: what do you mean?
[17-05-26 22:50:24][chat]: Socialdarwinist: pinkieval: The game is unbalanced anyway with two players, you cannot fix it …
[17-05-26 22:50:38][chat]: Socialdarwinist: I have to think
[17-05-26 22:50:57][chat]: Socialdarwinist: Isn’t a full zombie unbalanced against mercenary or a sniper
[17-05-26 22:51:09][chat]: Socialdarwinist: Or a medic
[17-05-26 22:51:22][chat]: pinkieval: I don't think so.
[17-05-26 22:51:31][chat]: pinkieval: anyway, it makes the game a bit more interesting
[17-05-26 22:51:36][chat]: Socialdarwinist: m_Armor = 10;
[17-05-26 22:51:38][chat]: Socialdarwinist: …
[17-05-26 22:51:48][chat]: pinkieval: ?
[17-05-26 22:51:52][chat]: Socialdarwinist: What about m_Armor = random_int(4,9);
[17-05-26 22:52:26][chat]: pinkieval: does it give a decent chance to defeat a scientist?
[17-05-26 22:52:53][chat]: Socialdarwinist: What about disallowing scientists if there are less than four players …
[17-05-26 22:53:02][chat]: pinkieval: hmm
[17-05-26 22:53:25][chat]: pinkieval: or limit it to one mine?
[17-05-26 22:53:31][chat]: Socialdarwinist: Also good
[17-05-26 22:53:34][chat]: pinkieval: and decrease the engineer's timeout
[17-05-26 22:53:44][chat]: Socialdarwinist: Okay
[17-05-26 22:54:00][chat]: Socialdarwinist: Because 10 armor every time is a bit heavy
[17-05-26 22:54:20][chat]: Socialdarwinist: Totally okay against scientists, but not else
[17-05-26 22:54:40][chat]: pinkieval: so, random armor + scientist and engie less op?
[17-05-26 22:55:14][chat]: Socialdarwinist: Less  op with fewer than 4 players or with 1 zombie?
[17-05-26 22:55:27][chat]: pinkieval: not sure
[17-05-26 22:55:35][chat]: Socialdarwinist: It can be dynamical: Less op, but again normal when 2 zombies there already
[17-05-26 22:56:10][chat]: pinkieval: depending on the map, an engie can be hard to defeat with only two zombies
[17-05-26 22:56:43][chat]: Socialdarwinist: Dunno, my maps are regularly hard because of their size and many places, not because of hard camps
[17-05-26 22:57:37][chat]: Socialdarwinist: I’ll post this chat to the Github issue for the posteriety
[17-05-26 22:57:44][chat]: pinkieval: great
[17-05-26 22:57:57][chat]: pinkieval: I was about to do it as well

```

**Comment by ProgVal** [comment]
Proposal:
* with one zombie, zombie gets armor in random(4, 9), engineer's wall lasts 10 seconds, scientist only has one mine
* with two zombies, zombies get armor in random(0, 9), engineer's wall lasts 20 seconds, scientist only has one mine

**Comment by Socialdarwinist** [comment]
Why should the scientist only have one mine if there are two infected already? One infected destroys the mine and the other goes through, or even both if the first survived as he had been healed. Note that having one mine only is awkward for a scientist if he has else two mines. Maybe you can decrease the damage done by scientist mines if there are less than five players and not more than two infected, the nerf would be less obtrusive.

**Comment by ProgVal** [comment]
> Why should the scientist only have one mine if there are two infected already? One infected destroys the mine and the other goes through, or even both if the first survived as he had been healed. Note that having one mine only is awkward for a scientist if he has else two mines.

Agreed.

> Maybe you can decrease the damage done by scientist mines if there are less than five players and not more than two infected, the nerf would be less obtrusive.

This is getting too complicated.

**Comment by Socialdarwinist** [comment]
@ProgVal I think I should merge this one if you include it in a config option whereby one can disable it. As it has become complicated, we won’t think out anything better.

**Pull request merged**
